version: '3'
services:
  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile
    tty: true
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    tty: true
  db:
    image: postgres:11-alpine3.15
    restart: always
    environment:
      POSTGRES_PASSWORD: example